const categoryData = {
  "Data Science": {
    tools: ["Power BI", "Excel", "Python", "SQL", "GenAI"],
    topics: {
      "Power BI": [
        "Approaching a Business Problem",
        "Connecting Various Data Sources",
        "Power Query",
        "Working with Different Data Types",
        "Data Modelling",
        "DAX Functions",
        "Creating Power BI Reports",
        "AI and Custom Visuals in Power BI",
        "Data Integration and Security",
      ],
      Excel: [
        "Data Hygiene",
        "Data Formatting, Filtering and Sorting",
        "Cell Referencing",
        "Basic Functions",
        "Date Functions",
        "Conditional Functions",
        "Database Functions",
        "Dynamic Arrays",
        "Logical Functions",
        "Lookup Functions",
        "Text Functions",
        "Pivot Tables",
        "Charts and Dashboards",
        "Conditional Formatting",
        "Data Validation",
        "Goal Seek and Solver",
      ],
      Python: [
        "Strings",
        "Lists",
        "Tuples",
        "Dictionary",
        "Sets",
        "If-Else",
        "For Loop",
        "While Loop",
        "Break, Pass and Continue on Loop",
        "User Defined Functions",
        "Working with Numpy",
        "Working with Dataframes in Pandas",
        "Handling Missing Values, Duplicates and Outliers",
        "Manipulating and Filtering Dataframes",
        "Bivariate Exploratory Data Analysis",
        "Linear Regression",
        "Logistic Regression",
        "Decision Tree",
        "Forecasting and Time Series Analysis",
        "Clustering",
      ],
      SQL: [
        "CRUD Operations",
        "Logical, Numerical and Comparison Operators",
        "Aggregate and Numerical Functions",
        "Conditional Statements",
        "Date Time Formatting and Functions",
        "Text Functions",
        "Pattern Matching",
        "Normalization",
        "Joins and Unions",
        "Group By and Having",
        "Pivoting, Rollup and User Defined Variables",
        "Common Table Expressions",
        "Window Functions",
        "Views and Stored Procedures",
        "Subqueries",
      ],
      GenAI: [
        "Introduction to Generative AI in Data Science",
        "AI-Powered Data Preprocessing",
        "Automated Data Cleaning with AI",
        "Generative AI for Synthetic Data Generation",
        "AI-Assisted Feature Engineering",
        "Using LLMs for Data Science Workflows",
        "AI-Driven Exploratory Data Analysis",
        "AI-Powered Hypothesis Testing",
        "Automating Model Selection and Hyperparameter Tuning",
        "AI-Driven Predictive Modeling",
        "AI-Based Forecasting in Time Series Analysis",
        "Text Generation and NLP Applications in Data Science",
        "AI for Image and Video Analytics",
        "Using Generative AI for Anomaly Detection",
        "Automated Insights and Report Generation",
        "AI in Recommendation Systems",
        "Ethical Considerations in AI-Generated Data"
      ]
      ,
      "Machine Learning": [
        "Random Forest",
        "Gradient Boosting Machines",
        "Ada Boost",
        "XGBoost",
        "KNN",
        "Support Vector Machine",
        "Naive Bayes",
        "Clustering",
        "Text Mining and Analytics",
        "Text Processing and Transform",
        "Natural Language Processing",
        "Artificial Neural Network",
        "Recurrent Neural Networks",
        "Convolutional Neural Networks",
      ],
      R: [
        "Working with Vectors",
        "Matrices",
        "Control Flow and Loops",
        "Working with Dataframes",
        "Math Functions",
        "Regular Expressions",
        "Dates and Timestamps",
        "Dplyr",
        "Tidyr",
        "Probability Distributions",
        "Hypothesis Testing",
        "ggplot",
        "Linear Regression",
        "Logistic Regression",
        "Decision Tree",
        "Forecasting and Time Series Analysis",
        "Clustering",
      ],
    },
  },
  "Data Engineering": {
    tools: [
      "SQL and Database Understanding",
      "Python",
      "Big Data Terminologies",
      "Data Warehousing",
      "Hadoop",
      "Apache Hive",
      "MongoDB",
      "Spark",
      "Kafka",
      "Cloud Essentials and Fundamentals of Azure",
      "Big Data in Azure",
    ],
    topics: {
      "SQL and Database Understanding": [
        "Database Design and Normalization",
        "SQL for Data Analysis",
        "Transactions and Concurrency Control",
        "Indexing and Query Optimization",
        "Stored Procedures and Triggers",
        "Data Modeling Concepts",
        "Advanced SQL Joins and Subqueries",
        "Database Security and Encryption",
        "SQL Performance Tuning",
      ],
      Python: [
        "Data Wrangling with Pandas",
        "Data Cleaning and Transformation",
        "ETL Process Implementation",
        "Data Visualization with Matplotlib and Seaborn",
        "Working with Large Datasets",
        "Python for Data Pipeline Automation",
        "Data Quality Checks in Python",
        "Connecting Python to Databases",
      ],
      "Big Data Terminologies": [
        "Overview of Big Data and its Characteristics",
        "Volume, Velocity, Variety, Veracity, Value",
        "Batch Processing vs. Stream Processing",
        "Data Ingestion Techniques",
        "Big Data Storage Solutions",
        "Data Processing and Analytics",
      ],
      "Data Warehousing": [
        "Introduction to Data Warehousing",
        "Dimensional Modeling",
        "Data Warehouse Architecture",
        "Star and Snowflake Schemas",
        "Data Warehouse Optimization",
        "ETL vs. ELT",
        "Data Mart Design",
        "Data Integration and Governance",
      ],
      Hadoop: [
        "Hadoop Ecosystem Overview",
        "HDFS (Hadoop Distributed File System)",
        "MapReduce Programming Model",
        "YARN (Yet Another Resource Negotiator)",
        "Hadoop Cluster Setup and Management",
        "Data Storage and Processing with Hadoop",
        "Hadoop for Batch Processing",
      ],
      "Apache Hive": [
        "Introduction to Apache Hive",
        "Hive Architecture and Components",
        "Writing SQL Queries in Hive",
        "Partitioning and Bucketing",
        "Optimizing Hive Queries",
        "Using Hive for Data Warehousing",
        "Hive vs. Traditional Databases",
      ],
      MongoDB: [
        "Introduction to NoSQL Databases",
        "Document-Oriented Data Models",
        "CRUD Operations in MongoDB",
        "Indexing and Aggregation in MongoDB",
        "Schema Design Best Practices",
        "MongoDB Replication and Sharding",
        "Data Consistency and Transactions",
      ],
      Spark: [
        "Apache Spark Overview",
        "RDDs (Resilient Distributed Datasets)",
        "DataFrames and Datasets",
        "Spark SQL for Data Processing",
        "Spark Streaming for Real-Time Data",
        "Machine Learning with Spark MLlib",
        "Optimizing Spark Jobs",
        "Spark on Hadoop",
      ],
      Kafka: [
        "Introduction to Apache Kafka",
        "Kafka Architecture and Components",
        "Producers and Consumers in Kafka",
        "Kafka Topics and Partitions",
        "Kafka Stream Processing",
        "Kafka Connect and Integration",
        "Building Real-Time Data Pipelines",
      ],
      "Cloud Essentials and Fundamentals of Azure": [
        "Azure Data Services Overview",
        "Data Storage Options in Azure",
        "Azure Data Lake Storage",
        "Azure SQL Database",
        "Setting Up Azure Virtual Machines",
        "Networking in Azure",
        "Security and Compliance in Azure",
        "Data Backup and Recovery on Azure",
      ],
      "Big Data in Azure": [
        "Introduction to Big Data on Azure",
        "Azure HDInsight for Big Data",
        "Azure Synapse Analytics",
        "Data Ingestion with Azure Data Factory",
        "Big Data Storage in Azure Blob Storage",
        "Real-Time Data Processing in Azure",
        "Analytics with Azure Databricks",
        "Building Scalable Data Pipelines on Azure",
      ],
    },
  },
  "Data Analytics": {
    tools: ["Power BI", "Excel", "Python", "SQL", "GenAI"],
    topics: {
      "Power BI": [
        "Approaching a Business Problem",
        "Connecting Various Data Sources",
        "Power Query",
        "Working with Different Data Types",
        "Data Modelling",
        "DAX Functions",
        "Creating Power BI Reports",
        "AI and Custom Visuals in Power BI",
        "Data Integration and Security",
      ],
      Excel: [
        "Data Hygiene",
        "Data Formatting, Filtering and Sorting",
        "Cell Referencing",
        "Basic Functions",
        "Date Functions",
        "Conditional Functions",
        "Database Functions",
        "Dynamic Arrays",
        "Logical Functions",
        "Lookup Functions",
        "Text Functions",
        "Pivot Tables",
        "Charts and Dashboards",
        "Conditional Formatting",
        "Data Validation",
        "Goal Seek and Solver",
      ],
      Python: [
        "Strings",
        "Lists",
        "Tuples",
        "Dictionary",
        "Sets",
        "If-Else",
        "For Loop",
        "While Loop",
        "Break, Pass and Continue on Loop",
        "User Defined Functions",
        "Working with Numpy",
        "Working with Dataframes in Pandas",
        "Handling Missing Values, Duplicates and Outliers",
        "Manipulating and Filtering Dataframes",
        "Bivariate Exploratory Data Analysis",
        "Linear Regression",
        "Logistic Regression",
        "Decision Tree",
        "Forecasting and Time Series Analysis",
        "Clustering",
      ],
      SQL: [
        "CRUD Operations",
        "Logical, Numerical and Comparison Operators",
        "Aggregate and Numerical Functions",
        "Conditional Statements",
        "Date Time Formatting and Functions",
        "Text Functions",
        "Pattern Matching",
        "Normalization",
        "Joins and Unions",
        "Group By and Having",
        "Pivoting, Rollup and User Defined Variables",
        "Common Table Expressions",
        "Window Functions",
        "Views and Stored Procedures",
        "Subqueries",
      ],
      GenAI: [
        "Introduction to Generative AI in Data Analytics",
        "Automating Data Cleaning and Preparation",
        "AI-Powered Data Visualization",
        "AI-Assisted Data Storytelling",
        "Generating Insights from Large Datasets",
        "AI-Driven Predictive Analytics",
        "Using LLMs for Data Analysis",
        "Building AI-Based Dashboards",
        "Generative AI for Business Intelligence",
        "Automating SQL Query Generation with AI",
        "Using AI for Anomaly Detection",
        "AI-Based Forecasting Techniques",
        "Natural Language Processing in Data Analysis",
        "AI-Driven Sentiment Analysis",
        "Automated Report Generation using AI",
        "AI-Powered Feature Engineering",
        "Ethics and Challenges of AI in Data Analytics"
      ],

      "Machine Learning": [
        "Random Forest",
        "Gradient Boosting Machines",
        "Ada Boost",
        "XGBoost",
        "KNN",
        "Support Vector Machine",
        "Naive Bayes",
        "Clustering",
        "Text Mining and Analytics",
        "Text Processing and Transform",
        "Natural Language Processing",
        "Artificial Neural Network",
        "Recurrent Neural Networks",
        "Convolutional Neural Networks",
      ],
      R: [
        "Working with Vectors",
        "Matrices",
        "Control Flow and Loops",
        "Working with Dataframes",
        "Math Functions",
        "Regular Expressions",
        "Dates and Timestamps",
        "Dplyr",
        "Tidyr",
        "Probability Distributions",
        "Hypothesis Testing",
        "ggplot",
        "Linear Regression",
        "Logistic Regression",
        "Decision Tree",
        "Forecasting and Time Series Analysis",
        "Clustering",
      ],
    },
  },
  GenAI: {
    tools: ["Beginner", "Intermediate", "Advanced"],
    topics: {
      Beginner: [
        "Introduction, How to Get API Keys",
        "Techniques to optimize API calls",
        "Implementing caching and request batching",
        "Using alternative APIs or fallback mechanisms",
        "Introduction to RAG (Retrieval-Augmented Generation)",
        "Optimizing the retrieval and generation processes",
        "Text Prompting Techniques: Single-word, full-sentence prompts",
        "Understand the fundamental concepts of chatbots.",
        "Learn how to design a chatbot’s workflow.",
        "Building Agents and Chains of Thought: Using Langchain library to build agents and manage workflows",
        "Tool Calling: Integrating external tools or APIs for enhanced functionality",
        "Memory and State Tracking: Managing state and memory within the application",
      ],
      Intermediate: [
        "Fine-tuning LLMs: Understanding when and how to fine-tune language models",
        "Customizing Prompts for Domain-Specific Applications",
        "Using Vector Databases for RAG Optimization",
        "Multi-Turn Conversations and Context Handling",
        "Building Custom AI Models with Open-Source Frameworks",
        "Integrating AI Models into Full-Stack Applications",
        "Sentiment Analysis and NLP Applications",
        "Building AI Assistants with LangChain and LlamaIndex",
        "Enhancing RAG Pipelines with Multi-Step Querying",
        "Building AI Agents for Task Automation",
        "Streaming Responses for Real-Time Applications"
      ],
      Advanced: [
        "Fine-Tuning Models with Custom Datasets",
        "Training LLMs from Scratch: Data collection, preprocessing, and model training",
        "Advanced RAG Architectures and Implementation",
        "Hybrid AI Models: Combining LLMs with Symbolic AI",
        "Memory-Augmented AI Systems",
        "Multi-Agent AI Systems and Collaboration",
        "AI-Orchestrated Workflows for Complex Decision-Making",
        "Scalability and Optimization of AI Models in Production",
        "Using Reinforcement Learning for AI Optimization",
        "Advanced Tool-Calling Techniques with AI Agents",
        "Deploying LLMs on Edge Devices and Serverless Architectures",
        "Security and Ethical Considerations in AI Applications"
      ],
    },
  },
};

export default categoryData;
